import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import "@fontsource/roboto"; // Font for Material-UI
import { CssBaseline, ThemeProvider, createTheme } from '@mui/material';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kaanch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
